# language: python
checks:
    python:
        typecheck_maybe_no_member: true
        duplicate_code: true
        code_rating: true
build:
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    -
                        command: pylint-run
                        use_website_config: true