language: python
python: 3.7.5
cache: pip
install: pip install -r requirements.txt
script: pytest -q test/tests.py
before_deploy:
- sed -i '/config.py/d' .gitignore > .gitignore
- sed -i '/credentials.json/d' .gitignore > .gitignore
- ls
- echo ----
- cat .gitignore
- git add .gitignore config.py credentials.json
- git commit -m 'Update .gitignore.'
deploy:
  provider: heroku
  api_key:
    secure: d7f5gCZKcQ+y2VU9mmXDOg4b2Kg8uin1hnuWru07bKdUywCRTVNL47JIhpv3YCFFVi9GJYyUO9TvTY2R6nA3CltXs8kTs3XR3sQ5cEO+MBFjjrpzuJdhU56FceN+Grg8Gaa1kCDF0+zAII9GSIezos+HG21D2uMvpImM0zmLq3wu5dPrhwc8NuxCocTHxFsWv77aUOACgxyQTL/0m8x1YQf+OR0IrY/c+vs31SVVRWXPY6JRp8uYNHapLnkUQejEG0OMmSuP+MDxKiWyh1kVCmpEiTsU7FnWhZwLOFOrBQXuonK6GSzU1Sg7FXHgLWvaWTZFP1+gr2e8QY61sTBYb75LBSGpgOy+bPgrcmbCji3ZABT7X67aslQjbPB/nHZyYUNQWZPd0xvSJiNlDUudSx3+Uy3nLwUhDIHFtFqeYAENQJ3mbGnFU32TsyDXk5G56QF1no1HMPnid+qjMZcp/rR0kSk/vXBlO43EfJrHuVp+EmCTnJhvxOdOlsULpj/ezARKJTGAmEW+creYnzQMh3R5u7PwvC29lN5aBzwGt2ZRNXtTtinWamS8v2SpRb0dk/Q5dJihG6P40e88S3JyjdJhmMrkaDGVYOi7iyktshxI/mlLbIxFn/G8wMXN86KxnBFYOYsKANOC0tvce4TJNYHp5P4swbnxKsXyt/sH3e8=
  app: dadyarri-ralph-2
notifications:
  email:
    recipients:
    - dadyarri@gmail.com
    on_success: never
    on_failure: always
