version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/projects/ralph
hooks:
  BeforeInstall:
    - location: scripts/remove.sh
      runas: ubuntu
  Install:
    - location: scripts/install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/restart.sh
      runas: ubuntu